server:
  port: 8089

spring:
  application:
    name: gateway-service
cloud:
  gateway:
    routes:
      - id: auth-service
        uri: http://localhost:8087
        predicates:
          - Path=/api/auth/**
      - id: User-profile
        uri: http://localhost:8081
        predicates:
          - Path=/profiles/**
        filters:
          - AuthenticationFilter


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/